const $=id=>document.getElementById(id);
const pretty=value=>JSON.stringify(value,null,2);
async function getJson(url){const response=await fetch(url,{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||`${response.status}`);return body}
async function requestJson(url,options){const response=await fetch(url,{cache:"no-store",...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||`${response.status}`);return body}
function renderCapabilities(items){const root=$("capabilities");root.textContent="";(items||[]).forEach(item=>{const node=document.createElement("div");node.className=`capability ${item.support_level||item.status||"blocked"}`;const title=document.createElement("strong");title.textContent=item.name||item.capability_id||item.id||"unknown";const detail=document.createElement("small");detail.textContent=`${item.support_level||item.status||"unknown"} · ${item.pool||item.reason||item.evidence||""}`;node.append(title,detail);root.append(node)})}
async function refresh(){let platform=null,device=null;try{platform=await getJson("/api/controller/v1/platform");$("platform-json").textContent=pretty(platform);$("android-version").textContent=`${platform.android_version||"—"} / API ${platform.api_level||"—"}`;$("image-kind").textContent=platform.system_image_kind||"—";$("runtime-mode").textContent=platform.runtime_mode||"—";$("kvm-status").textContent=platform.kvm_available?"KVM available":"KVM unavailable";$("evidence-state").textContent=platform.evidence_status||"—";const capabilities=await getJson("/api/controller/v1/capabilities");renderCapabilities(capabilities.capabilities||capabilities);const sessions=await getJson("/api/controller/v1/sessions");$("sessions-json").textContent=pretty(sessions)}catch(error){$("platform-json").textContent=`controller: ${error.message}`}try{device=await getJson("/api/device/healthz");$("device-state").textContent=device.ready?"READY":"STARTING";$("device-product").textContent=device.properties?.product||device.state||"—"}catch(error){$("device-state").textContent="OFFLINE";$("device-product").textContent=error.message}const ready=Boolean(device?.ready);const overall=$("overall");overall.className=`badge ${ready?"ready":platform?.runtime_mode==="blocked"?"blocked":"pending"}`;overall.textContent=ready?"设备就绪":platform?.runtime_mode==="blocked"?"环境阻断":"等待设备";$("updated-at").textContent=new Date().toLocaleTimeString()}
async function refreshScreen(){const img=$("screen");img.classList.remove("visible");img.onload=()=>img.classList.add("visible");img.src=`/api/device/v1/screenshot.png?t=${Date.now()}`}
const controlStatus=message=>$("control-status").textContent=message;
const currentToken=()=>sessionStorage.getItem("bridge-token")||"";
async function devicePost(path,body){const token=currentToken();if(!token)throw new Error("请先输入控制令牌");return requestJson(`/api/device${path}`,{method:"POST",headers:{"Authorization":`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)})}
$("save-token").addEventListener("click",()=>{const token=$("bridge-token").value.trim();if(token){sessionStorage.setItem("bridge-token",token);$("bridge-token").value="";controlStatus("令牌已保存到当前标签页。") }else{sessionStorage.removeItem("bridge-token");controlStatus("当前标签页令牌已清除。")}});
$("screen").addEventListener("click",async event=>{const img=event.currentTarget;if(!img.naturalWidth||!img.naturalHeight)return;const rect=img.getBoundingClientRect();const scale=Math.min(rect.width/img.naturalWidth,rect.height/img.naturalHeight);const width=img.naturalWidth*scale,height=img.naturalHeight*scale;const left=rect.left+(rect.width-width)/2,top=rect.top+(rect.height-height)/2;if(event.clientX<left||event.clientX>left+width||event.clientY<top||event.clientY>top+height)return;const x=Math.round((event.clientX-left)/scale),y=Math.round((event.clientY-top)/scale);try{await devicePost("/v1/input/tap",{x,y});controlStatus(`已发送触控：${x}, ${y}`);setTimeout(refreshScreen,350)}catch(error){controlStatus(error.message)}});
document.querySelectorAll("[data-keycode]").forEach(button=>button.addEventListener("click",async()=>{try{await devicePost("/v1/input/keyevent",{keycode:Number(button.dataset.keycode)});controlStatus(`已发送：${button.textContent}`);setTimeout(refreshScreen,350)}catch(error){controlStatus(error.message)}}));
$("send-text").addEventListener("click",async()=>{try{await devicePost("/v1/input/text",{text:$("input-text").value});$("input-text").value="";controlStatus("文本已发送。");setTimeout(refreshScreen,350)}catch(error){controlStatus(error.message)}});
$("create-session").addEventListener("click",async()=>{try{const key=`dashboard-${crypto.randomUUID()}`;await requestJson("/api/controller/v1/sessions",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({client_reference:"dashboard",lease_seconds:3600,requested_capabilities:["android_framework","google_play_store","adb"]})});await refresh()}catch(error){$("sessions-json").textContent=`session: ${error.message}`}});
$("refresh-screen").addEventListener("click",refreshScreen);refresh();setInterval(refresh,10000);setInterval(()=>{if($("device-state").textContent==="READY")refreshScreen()},5000);
